version: "3"

services:
  node:
    image: node:16.15.1-alpine
    container_name: brokerage
    volumes:
      - ./:/app
    tty: true
    stdin_open: true
    working_dir: /app
    # command: bash
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      NODE_PORT: 3000
      DB_URL: postgres://postgres:password@db:5432/brokerage
      JWT_SECRET: secretJWT
      SALT_ROUNDS: 10
  db:
    container_name: postgres_db
    image: postgres:14.4-alpine
    platform: linux/x86_64
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password