version: "3"

services:
  node:
    image: node:16.15.1-alpine
    container_name: brokerage
    volumes:
      - ./:/app
    tty: true
    stdin_open: true
    working_dir: /app
    # command: bash
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      DB_URL: postgres://postgres:password@db:5432/brokerage
      JWT_SECRET: c8fe4924c6dab50b726c513e16598757da6a595bd6b2f390c587030bb4951ff8
      SALT_ROUNDS: 10
  db:
    container_name: postgres_db
    image: postgres:14.4-alpine
    platform: linux/x86_64
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
  db_test:
    container_name: postgres_db_test
    image: postgres:14.4-alpine
    platform: linux/x86_64
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: password